print("Welcome to Band Name Generator")
city = input("What's the name of the city you grew up in?")
print(city)
pet = input("What's your pet name?")
print(pet)
print("Your Band name is" + " " + city + " " + pet)